# Generated by Django 2.2.24 on 2021-10-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedSubscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('feeds', models.ManyToManyField(blank=True, related_name='subscribers', to='feed.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_items', to='feed.FeedItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
