# Generated by Django 2.2.24 on 2021-10-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feeditem_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedsubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
